services:
  frontend:
    build: 
      context: ./frontend
      args:
        - NODE_ENV=${NODE_ENV}
    env_file:
      - ./.env
      - ./.env.${NODE_ENV}
    volumes:
      - ./frontend:/frontend
      - ./node_modules:/frontend/node_modules
    depends_on:
      - backend
    networks:
      - app-network
    ports:
      - '3000:3000'

  backend:
    build: 
      context: ./backend
      args:
        - NODE_ENV=${NODE_ENV}
    env_file:
      - ./.env
      - ./.env.${NODE_ENV}
    volumes:
      - ./backend:/backend
      - ./node_modules:/backend/node_modules
    depends_on:
      - postgres
    networks:
      - app-network
    ports:
      - '3001:3001'
      
  pgadmin:
    image: dpage/pgadmin4
    env_file:
      - ./.env
      - ./.env.${NODE_ENV}
    ports:
      - "8080:80"
    depends_on:
      - postgres
    networks:
      - app-network

  postgres:
    image: postgres:alpine
    env_file:
      - ./.env
      - ./.env.${NODE_ENV}
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data
    user: "${UID}:${GID}"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge